# Generated by Django 2.1.5 on 2019-01-17 13:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_auto_20190116_0922'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('name', 'user')},
        ),
    ]
