export const BASE_URL = `/api/v1`;

// User
export const FETCH_USER = 'FETCH_USER';
export const USER_SUCCESSFULLY_LOGGED_IN = 'USER_SUCCESSFULLY_LOGGED_IN';
export const USER_SUCCESSFULLY_LOGGED_OUT = 'USER_SUCCESSFULLY_LOGGED_OUT';
export const BAD_AUTH_CREDENTIALS = 'BAD_AUTH_CREDENTIALS';
export const USER_SUCCESSFULLY_CREATED = 'USER_SUCCESSFULLY_CREATED';
export const USER_COULD_NOT_BE_CREATED = 'USER_COULD_NOT_BE_CREATED';

// Tasks
export const FETCH_TASKS = 'FETCH_TASKS';
export const TASK_SUCCESSFULLY_CREATED = 'TASK_SUCCESSFULLY_CREATED';
export const TASK_COULD_NOT_BE_CREATED = 'TASK_COULD_NOT_BE_CREATED';
export const TASK_DELETED = 'TASK_DELETED';
export const TASK_SUCCESSFULLY_UPDATED = 'TASK_SUCCESSFULLY_UPDATED';

// Settings
export const SETTINGS_UPDATED = 'SETTINGS_UPDATED';

